Adding comments. Minor restructuring of ancestry-specific chip cleaning pipeline that will not affect output

diff --git a/Makefile.config b/Makefile.config
--- a/Makefile.config
+++ b/Makefile.config
@@ -1,1 +1,71 @@
-BGEN_DIR := ./bgen
+PROJECT_BASE_DIR := /CGF/GWAS/Scans/PLCO/builds/1/plco-analysis
+
+PLATFORMS := OmniX Omni25 Omni5 Oncoarray $(patsubst %,GSA_batch%,$(shell seq 1 5))
+CHIP_FREEZE_INPUT_DIR := $(PROJECT_BASE_DIR)/../current-chip-final-subjects
+EXTERNAL_FILE_INPUT_DIR := $(PROJECT_BASE_DIR)/external-files
+FILTERED_IMPUTED_INPUT_DIR := $(PROJECT_BASE_DIR)/../filtered-dosage-data
+CONFIG_INPUT_DIR := $(PROJECT_BASE_DIR)/config
+
+BGEN_OUTPUT_DIR := $(PROJECT_BASE_DIR)/bgen
+CLEANED_CHIP_OUTPUT_DIR := $(PROJECT_BASE_DIR)/cleaned-chips-by-ancestry
+ANCESTRY_OUTPUT_DIR := $(PROJECT_BASE_DIR)/ancestry
+RELATEDNESS_OUTPUT_DIR := $(PROJECT_BASE_DIR)/relatedness
+FASTGWA_GRM_OUTPUT_DIR := $(PROJECT_BASE_DIR)/fastgwa-grm
+CHRS := $(shell seq 1 22)
+UNIQUE_SUBJECT_LIST := $(EXTERNAL_FILE_INPUT_DIR)/PLCO_final_subject_list_Ancestry_UniqGenotypePlatform_04132020.txt
+
+PHENOTYPE_FILENAME := $(PROJECT_BASE_DIR)/phenotypes/v5/gsa_qx_v5.with_na.augmented.18may2020.tsv
+
+N_THREADS := 2
+
+## supported software
+PLINK_MEMORY_LIMIT := 16000
+PLINK19 := plink --memory $(PLINK_MEMORY_LIMIT)
+PLINK2 := /home/palmercd/Development/plink2/plink2 --memory $(PLINK_MEMORY_LIMIT)
+BGENIX := /CGF/Bioinformatics/Production/palmercd/bgen/gavinband-bgen-44fcabbc5c38/build/apps/bgenix
+GCTA := /home/palmercd/Development/gcta_1.93.1beta/gcta64
+SMARTPCA := /home/palmercd/Development/EIG-6.1.4/bin/smartpca
+
+GRAF_INSTALL_PREFIX := /CGF/Bioinformatics/Production/palmercd/GRAF/GRAF
+
+GRAF_EXECUTABLE := $(GRAF_INSTALL_PREFIX)/graf
+GRAF_POP := $(GRAF_INSTALL_PREFIX)/PlotPopulations.pl
+GRAF_1KG_VARIANT_BIMFILE := $(GRAF_INSTALL_PREFIX)/G1000FpGeno.bim
+CLEANED_ANCESTRY_NAMES := European East_Asian Other South_Asian African_American Hispanic1 Hispanic2
+
+
+QSUB_JOB_MONITOR := /home/palmercd/Development/stage/bin/qsub_job_monitor.out
+ACTIVE_JOB_MONITOR := $(QSUB_JOB_MONITOR)
+
+SUPPORTED_METHODS := saige boltlmm fastgwa
+
+## software subject count restrictions
+FASTGWA_MINIMUM_VALID_SUBJECT_COUNT := 2000
+
+
+
+## chip cleaning parameters
+HET_F_MAX := 0.2
+PIHAT_MIN := 0.05
+SAMPLE_SIZE_MIN := 10
+SAMPLE_SIZE_LARGE := 10000
+GENOME_GZ_JOB_SPLIT := 20
+
+
+
+
+## utility functions
+define qsub_handler =
+echo -e "$(2) \nif [[ \"\$$?\" -eq \"0\" ]] ; then \n\ttouch $(1).success\nelse\n\ttouch $(1).fail \nfi\nexit 0" > $(1).command.bash ; \
+$(ACTIVE_JOB_MONITOR) -o $(1) -r h_rt=23:10:00 -q all.q -c $(1).command.bash -t 10
+endef
+
+define qsub_handler_long =
+echo -e "$(2) \nif [[ \"\$$?\" -eq \"0\" ]] ; then \n\ttouch $(1).success\nelse\n\ttouch $(1).fail \nfi\nexit 0" > $(1).command.bash ; \
+$(ACTIVE_JOB_MONITOR) -o $(1) -r h_rt=71:00:00 -q long.q -c $(1).command.bash -t 10
+endef
+
+define qsub_handler_specify_queue_time =
+echo -e "$(2) \nif [[ \"\$$?\" -eq \"0\" ]] ; then \n\ttouch $(1).success\nelse\n\ttouch $(1).fail \nfi\nexit 0" > $(1).command.bash ; \
+$(ACTIVE_JOB_MONITOR) -o $(1) -r h_rt=$(if $(4),$(4),23:00:00) -q $(if $(3),$(3),all.q) -c $(1).command.bash -t 10
+endef
